echo 1 | ./leapyear1.c
echo 2 | ./leapyear1.c
echo 3 | ./leapyear1.c
echo 4 | ./leapyear1.c
echo 5 | ./leapyear1.c
echo 6 | ./leapyear1.c
echo 7 | ./leapyear1.c
echo 8 | ./leapyear1.c
echo 9 | ./leapyear1.c
echo 10 | ./leapyear1.c